scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'Node Exporter'
    consul_sd_configs:
      - server: 'localhost:8500'
    relabel_configs:
      - source_labels: ['__meta_consul_service']
        regex: '(.*)'
        target_label: service
      - source_labels: ['__meta_consul_tags']
        regex: '.*,k8s,.*'
        action: drop
      - source_labels: ['__address__']
        separator: ':'
        regex: '(.*):(.*)'
        target_label: '__address__'
        replacement: '$1:9100'
  - job_name: 'consul-service'
    consul_sd_configs:
      - server: 'localhost:8500'
    metrics_path: '/v1/agent/metrics'
    params:
      format: ['prometheus']
    relabel_configs:
      - source_labels: ['__meta_consul_service']
        regex: '(^consul)'
        target_label: job
        action: 'keep'
      - source_labels: ['__address__']
        separator: ';'
        regex: '(.*):(.*)'
        target_label: '__address__'
        replacement: '$1:8500'
  - job_name: 'jenkins'
    metrics_path: '/prometheus/'
    scheme: http
    bearer_token: <bearer_token>
    static_configs:
        - targets: ['jenkins-webserver.service.consul:8080']
  - job_name: 'Mysql Exporter'
    consul_sd_configs:
      - server: 'localhost:8500'
    relabel_configs:
      - source_labels: ['__meta_consul_tags']
        regex: '.*mysql.*'
        target_label: job
        action: 'keep'
      - source_labels: ['__address__']
        separator: ':'
        regex: '(.*):(.*)'
        target_label: '__address__'
        replacement: '$1:9104'
  - job_name: 'Application Web Site'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://project-svc-default.service.consul:80
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115
 

